// <auto-generated />
using System;
using Alumni_Management_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Alumni_Management_System.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260215010000_AddIsFirstLoginToAppUser")]
    partial class AddIsFirstLoginToAppUser
    {

        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Alumni_Management_System.Models.Alumni", b =>
                {
                    b.Property<int>("AlumniId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("alumni_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlumniId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("country");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("gender");

                    b.Property<int>("GraduationYear")
                        .HasColumnType("int")
                        .HasColumnName("graduation_year");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("JagId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("jag_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_name");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("last_updated")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PermanentEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("permanent_email");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Postcode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("postcode");

                    b.Property<string>("PreferredFirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("preferred_first_name");

                    b.Property<string>("Prefix")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("prefix");

                    b.Property<bool>("Privacy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("privacy");

                    b.Property<string>("SocialMediaAccount")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("social_media_account");

                    b.Property<bool>("SolicitationCode")
                        .HasColumnType("bit")
                        .HasColumnName("solicitation_code");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("state");

                    b.Property<string>("StudentEmail")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("student_email");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.HasKey("AlumniId")
                        .HasName("PK__Alumni__BB1DF35C3C7BFE94");

                    b.HasIndex("JagId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[user_id] IS NOT NULL");

                    b.HasIndex(new[] { "JagId" }, "UQ__Alumni__FBF400ED6AB71E0A")
                        .IsUnique();

                    b.ToTable("Alumni");
                });

            modelBuilder.Entity("Alumni_Management_System.Models.AlumniDegree", b =>
                {
                    b.Property<int>("AlumniDegreeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("alumni_degree_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlumniDegreeId"));

                    b.Property<int>("AlumniId")
                        .HasColumnType("int")
                        .HasColumnName("alumni_id");

                    b.Property<bool?>("AttendedOrPlansGradSchool")
                        .HasColumnType("bit")
                        .HasColumnName("attended_or_plans_grad_school");

                    b.Property<DateOnly>("DateConferred")
                        .HasColumnType("date")
                        .HasColumnName("date_conferred");

                    b.Property<int>("DegreeId")
                        .HasColumnType("int")
                        .HasColumnName("degree_id");

                    b.Property<bool?>("DegreeSpecificJob")
                        .HasColumnType("bit")
                        .HasColumnName("degree_specific_job");

                    b.Property<string>("EmploymentWhileStudying")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("employment_while_studying");

                    b.Property<decimal?>("Gpa")
                        .HasColumnType("decimal(3, 2)")
                        .HasColumnName("gpa");

                    b.Property<bool?>("JobSecuredUponGraduation")
                        .HasColumnType("bit")
                        .HasColumnName("job_secured_upon_graduation");

                    b.Property<bool?>("ParticipatedInResearch")
                        .HasColumnType("bit")
                        .HasColumnName("participated_in_research");

                    b.Property<int?>("YearsToCompleteDegree")
                        .HasColumnType("int")
                        .HasColumnName("years_to_complete_degree");

                    b.HasKey("AlumniDegreeId")
                        .HasName("PK__Alumni_D__F0FA85104CA70CF5");

                    b.HasIndex("AlumniId");

                    b.HasIndex("DegreeId");

                    b.ToTable("Alumni_Degrees");
                });

            modelBuilder.Entity("Alumni_Management_System.Models.AlumniEmployment", b =>
                {
                    b.Property<int>("AlumniEmploymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("alumni_employment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlumniEmploymentId"));

                    b.Property<int>("AlumniId")
                        .HasColumnType("int")
                        .HasColumnName("alumni_id");

                    b.Property<int>("EmployerId")
                        .HasColumnType("int")
                        .HasColumnName("employer_id");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("job_title");

                    b.Property<string>("SalaryRange")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("salary_range");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("AlumniEmploymentId")
                        .HasName("PK__Alumni_E__22E422E8BDA6C801");

                    b.HasIndex("AlumniId");

                    b.HasIndex("EmployerId");

                    b.ToTable("Alumni_Employment");
                });

            modelBuilder.Entity("Alumni_Management_System.Models.AlumniInternship", b =>
                {
                    b.Property<int>("AlumniInternshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("alumni_internship_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlumniInternshipId"));

                    b.Property<int>("AlumniId")
                        .HasColumnType("int")
                        .HasColumnName("alumni_id");

                    b.Property<int>("EmployerId")
                        .HasColumnType("int")
                        .HasColumnName("employer_id");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("InternshipType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("internship_type");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("title");

                    b.HasKey("AlumniInternshipId")
                        .HasName("PK__Alumni_I__FFE040B307B79B52");

                    b.HasIndex("AlumniId");

                    b.HasIndex("EmployerId");

                    b.ToTable("Alumni_Internships");
                });

            modelBuilder.Entity("Alumni_Management_System.Models.AlumniMessage", b =>
                {
                    b.Property<int>("AlumniMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("alumni_message_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlumniMessageId"));

                    b.Property<int>("AlumniId")
                        .HasColumnType("int")
                        .HasColumnName("alumni_id");

                    b.Property<int>("MessageId")
                        .HasColumnType("int")
                        .HasColumnName("message_id");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("sent_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("AlumniMessageId")
                        .HasName("PK__Alumni_M__E6B241004CC7DEC9");

                    b.HasIndex("AlumniId");

                    b.HasIndex("MessageId");

                    b.ToTable("Alumni_Messages");
                });

            modelBuilder.Entity("Alumni_Management_System.Models.AlumniOrganization", b =>
                {
                    b.Property<int>("AlumniOrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("alumni_organization_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlumniOrganizationId"));

                    b.Property<int>("AlumniId")
                        .HasColumnType("int")
                        .HasColumnName("alumni_id");

                    b.Property<string>("OfficerRoles")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("officer_roles");

                    b.Property<int>("OrganizationTypeId")
                        .HasColumnType("int")
                        .HasColumnName("organization_type_id");

                    b.HasKey("AlumniOrganizationId")
                        .HasName("PK__Alumni_O__8366569D1933C852");

                    b.HasIndex("AlumniId");

                    b.HasIndex("OrganizationTypeId");

                    b.ToTable("Alumni_Organizations");
                });

            modelBuilder.Entity("Alumni_Management_System.Models.AlumniRegistry", b =>
                {
                    b.Property<int>("RegistryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("registry_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistryId"));

                    b.Property<bool>("AccountCreated")
                        .HasColumnType("bit")
                        .HasColumnName("account_created");

                    b.Property<string>("DegreeProgram")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("degree_program");

                    b.Property<string>("EmailOnRecord")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email_on_record");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_name");

                    b.Property<int?>("GraduationYear")
                        .HasColumnType("int")
                        .HasColumnName("graduation_year");

                    b.Property<string>("JagId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("jag_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_name");

                    b.HasKey("RegistryId")
                        .HasName("PK__Alumni_R__EF8E9CE8B1C6B2D8");

                    b.HasIndex(new[] { "JagId" }, "UQ__Alumni_R__FBF400ED39BA228D")
                        .IsUnique();

                    b.ToTable("Alumni_Registry");
                });

            modelBuilder.Entity("Alumni_Management_System.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFirstLogin")
                        .HasColumnType("bit")
                        .HasColumnName("is_first_login");

                    b.Property<string>("JagId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Alumni_Management_System.Models.DegreeProgram", b =>
                {
                    b.Property<int>("DegreeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("degree_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DegreeId"));

                    b.Property<string>("DegreeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("degree_type");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("department");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("institution");

                    b.Property<string>("MajorFieldOfStudy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("major_field_of_study");

                    b.HasKey("DegreeId")
                        .HasName("PK__Degree_P__A1AFAEBBB780871C");

                    b.ToTable("Degree_Programs");
                });

            modelBuilder.Entity("Alumni_Management_System.Models.Employer", b =>
                {
                    b.Property<int>("EmployerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("employer_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployerId"));

                    b.Property<string>("EmployerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("employer_name");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("industry");

                    b.Property<string>("Location")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("location");

                    b.HasKey("EmployerId")
                        .HasName("PK__Employer__365FA4E7DF9F3065");

                    b.ToTable("Employers");
                });

            modelBuilder.Entity("Alumni_Management_System.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("message_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("created_by");

                    b.Property<string>("MessageBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message_body");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("message_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("title");

                    b.HasKey("MessageId")
                        .HasName("PK__Messages__0BBF6EE63BAB61CB");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Alumni_Management_System.Models.OrganizationType", b =>
                {
                    b.Property<int>("OrganizationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("organization_type_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrganizationTypeId"));

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("organization_name");

                    b.HasKey("OrganizationTypeId")
                        .HasName("PK__Organiza__466C7A244B987C0F");

                    b.ToTable("Organization_Types");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Alumni_Management_System.Models.Alumni", b =>
                {
                    b.HasOne("Alumni_Management_System.Models.AppUser", "User")
                        .WithOne("Alumni")
                        .HasForeignKey("Alumni_Management_System.Models.Alumni", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Alumni_Management_System.Models.AlumniDegree", b =>
                {
                    b.HasOne("Alumni_Management_System.Models.Alumni", "Alumni")
                        .WithMany("AlumniDegrees")
                        .HasForeignKey("AlumniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ad_alumni");

                    b.HasOne("Alumni_Management_System.Models.DegreeProgram", "Degree")
                        .WithMany("AlumniDegrees")
                        .HasForeignKey("DegreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ad_degree");

                    b.Navigation("Alumni");

                    b.Navigation("Degree");
                });

            modelBuilder.Entity("Alumni_Management_System.Models.AlumniEmployment", b =>
                {
                    b.HasOne("Alumni_Management_System.Models.Alumni", "Alumni")
                        .WithMany("AlumniEmployments")
                        .HasForeignKey("AlumniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ae_alumni");

                    b.HasOne("Alumni_Management_System.Models.Employer", "Employer")
                        .WithMany("AlumniEmployments")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ae_employer");

                    b.Navigation("Alumni");

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("Alumni_Management_System.Models.AlumniInternship", b =>
                {
                    b.HasOne("Alumni_Management_System.Models.Alumni", "Alumni")
                        .WithMany("AlumniInternships")
                        .HasForeignKey("AlumniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_alumni");

                    b.HasOne("Alumni_Management_System.Models.Employer", "Employer")
                        .WithMany("AlumniInternships")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_employer");

                    b.Navigation("Alumni");

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("Alumni_Management_System.Models.AlumniMessage", b =>
                {
                    b.HasOne("Alumni_Management_System.Models.Alumni", "Alumni")
                        .WithMany("AlumniMessages")
                        .HasForeignKey("AlumniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_am_alumni");

                    b.HasOne("Alumni_Management_System.Models.Message", "Message")
                        .WithMany("AlumniMessages")
                        .HasForeignKey("MessageId")
                        .IsRequired()
                        .HasConstraintName("fk_am_message");

                    b.Navigation("Alumni");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Alumni_Management_System.Models.AlumniOrganization", b =>
                {
                    b.HasOne("Alumni_Management_System.Models.Alumni", "Alumni")
                        .WithMany("AlumniOrganizations")
                        .HasForeignKey("AlumniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ao_alumni");

                    b.HasOne("Alumni_Management_System.Models.OrganizationType", "OrganizationType")
                        .WithMany("AlumniOrganizations")
                        .HasForeignKey("OrganizationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ao_org");

                    b.Navigation("Alumni");

                    b.Navigation("OrganizationType");
                });

            modelBuilder.Entity("Alumni_Management_System.Models.Message", b =>
                {
                    b.HasOne("Alumni_Management_System.Models.AppUser", "CreatedByNavigation")
                        .WithMany("Messages")
                        .HasForeignKey("CreatedBy");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Alumni_Management_System.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Alumni_Management_System.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alumni_Management_System.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Alumni_Management_System.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Alumni_Management_System.Models.Alumni", b =>
                {
                    b.Navigation("AlumniDegrees");

                    b.Navigation("AlumniEmployments");

                    b.Navigation("AlumniInternships");

                    b.Navigation("AlumniMessages");

                    b.Navigation("AlumniOrganizations");
                });

            modelBuilder.Entity("Alumni_Management_System.Models.AppUser", b =>
                {
                    b.Navigation("Alumni");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Alumni_Management_System.Models.DegreeProgram", b =>
                {
                    b.Navigation("AlumniDegrees");
                });

            modelBuilder.Entity("Alumni_Management_System.Models.Employer", b =>
                {
                    b.Navigation("AlumniEmployments");

                    b.Navigation("AlumniInternships");
                });

            modelBuilder.Entity("Alumni_Management_System.Models.Message", b =>
                {
                    b.Navigation("AlumniMessages");
                });

            modelBuilder.Entity("Alumni_Management_System.Models.OrganizationType", b =>
                {
                    b.Navigation("AlumniOrganizations");
                });
#pragma warning restore 612, 618
        }
    }
}
